(() => {
  const $ = (s) => document.querySelector(s);
  const conversation = $('#conversation'), messages = $('#messages'), welcome = $('#welcome'), form = $('#chatForm'), prompt = $('#prompt'), send = $('#sendButton'), loading = $('#loading');
  const KEY = 'sprout.v1';
  let data = load(), activeChat = null, busy = false;
  function load(){try{return JSON.parse(localStorage.getItem(KEY))||{notes:[],chats:[]}}catch{return{notes:[],chats:[]}}}
  function persist(){localStorage.setItem(KEY,JSON.stringify(data));renderHistory();renderNotes()}
  function id(){return Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
  function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function renderHistory(){const root=$('#history');root.innerHTML='';data.chats.slice().reverse().slice(0,30).forEach(chat=>{const b=document.createElement('button');b.className='history-item';b.textContent=chat.title;b.title=chat.title;b.onclick=()=>openChat(chat.id);root.append(b)})}
  function renderNotes(){ $('#memoryCount').textContent=data.notes.length;const root=$('#savedNotes');root.innerHTML='';data.notes.forEach((n,i)=>{const row=document.createElement('div');row.className='note-entry';row.innerHTML=`<span>✎ &nbsp;${esc(n.title)}</span><button data-remove="${i}">Remove</button>`;root.append(row)});root.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{data.notes.splice(+b.dataset.remove,1);persist()}) }
  function showMessage(role,text,sources=[]){const wrap=document.createElement('div');wrap.className=`message ${role}`;if(role==='assistant'){wrap.innerHTML='<div class="message-avatar">✳</div><div class="bubble"></div>';wrap.querySelector('.bubble').innerHTML=paragraphs(text);if(sources.length){const row=document.createElement('div');row.className='source-row';row.innerHTML='<span class="source-label">Sources</span>';sources.forEach(s=>{const a=document.createElement('a');a.className='source-chip';a.href=s.url;a.target='_blank';a.rel='noopener noreferrer';a.textContent=s.title;row.append(a)});wrap.querySelector('.bubble').append(row)}}else{wrap.innerHTML=`<div class="bubble">${esc(text)}</div>`}messages.append(wrap);conversation.scrollTop=conversation.scrollHeight}
  function paragraphs(s){return String(s).split(/\n\n+/).filter(Boolean).map(p=>`<p>${esc(p).replace(/\n/g,'<br>')}</p>`).join('')}
  function openChat(chatId){const chat=data.chats.find(c=>c.id===chatId);if(!chat)return;activeChat=chat.id;messages.innerHTML='';welcome.hidden=true;chat.messages.forEach(m=>showMessage(m.role,m.text,m.sources||[]));$('#sidebar').classList.remove('open');$('#overlay').classList.remove('show')}
  function fresh(){activeChat=null;messages.innerHTML='';welcome.hidden=false;prompt.focus();$('#sidebar').classList.remove('open');$('#overlay').classList.remove('show')}
  function saveTurn(role,text,sources=[]){let chat=data.chats.find(c=>c.id===activeChat);if(!chat){chat={id:id(),title:text.slice(0,46)+(text.length>46?'…':''),messages:[]};data.chats.push(chat);activeChat=chat.id}chat.messages.push({role,text,sources});persist()}
  function terms(q){return q.replace(/[?!.,:;()[\]{}"']/g,' ').split(/\s+/).filter(w=>w.length>3&&!/^(what|when|where|which|would|could|should|explain|tell|about|does|with|from|that|this|have|into|your|please|simple|terms)$/i.test(w)).slice(0,6).join(' ')}
  async function wiki(q){const search=new URL('https://en.wikipedia.org/w/api.php');search.search=new URLSearchParams({action:'query',list:'search',srsearch:terms(q)||q,srlimit:'5',format:'json',origin:'*'});const r=await fetch(search);if(!r.ok)throw Error('Wikipedia search is unavailable');const j=await r.json();const hits=j.query?.search||[];if(!hits.length)return[];const pages=new URL('https://en.wikipedia.org/w/api.php');pages.search=new URLSearchParams({action:'query',pageids:hits.slice(0,4).map(x=>x.pageid).join('|'),prop:'extracts',exintro:'1',explaintext:'1',exchars:'1700',format:'json',origin:'*'});const pr=await fetch(pages);if(!pr.ok)throw Error('Wikipedia pages are unavailable');const pj=await pr.json();return hits.slice(0,4).map(h=>({title:h.title,extract:(pj.query?.pages?.[h.pageid]?.extract||'').replace(/\s+/g,' ').trim(),url:'https://en.wikipedia.org/?curid='+h.pageid})).filter(x=>x.extract)}
  function relevantNotes(q){const words=terms(q).toLowerCase().split(' ');return data.notes.filter(n=>{const blob=(n.title+' '+n.body).toLowerCase();return words.some(w=>blob.includes(w))}).slice(0,3)}
  function compose(q,pages,notes){if(!pages.length&&!notes.length)return 'I couldn’t find a useful Wikipedia page for that question. Try asking with a couple of specific keywords, or teach me a note about it.';let chunks=[];for(const p of pages){let sentences=p.extract.match(/[^.!?]+[.!?]+|[^.!?]+$/g)||[p.extract];let termsQ=terms(q).toLowerCase().split(' ').filter(Boolean);let ranked=sentences.map((s,i)=>({s:s.trim(),i,score:termsQ.reduce((v,w)=>v+(s.toLowerCase().includes(w)?1:0),0)})).sort((a,b)=>b.score-a.score||a.i-b.i).slice(0,2).sort((a,b)=>a.i-b.i);const text=ranked.map(x=>x.s).join(' ');if(text)chunks.push(text)}let answer=chunks.slice(0,3).join('\n\n');if(notes.length){const noteText=notes.map(n=>`${n.title}: ${n.body}`).join('\n');if(answer)answer='I found this in open references:\n\n'+answer+'\n\nYour notes add: '+noteText;else answer='From your notes: '+noteText}return answer}
  async function ask(q){if(busy||!q.trim())return;busy=true;welcome.hidden=true;showMessage('user',q);saveTurn('user',q);prompt.value='';resize();send.disabled=true;loading.hidden=false;conversation.scrollTop=conversation.scrollHeight;let pages=[],notes=relevantNotes(q),answer;try{pages=await wiki(q);answer=compose(q,pages,notes)}catch(e){answer=notes.length?compose(q,[],notes):'I couldn’t reach Wikipedia just now. Check your connection and try again. You can still teach me notes using “Teach Sprout”.'}loading.hidden=true;showMessage('assistant',answer,pages.map(p=>({title:p.title,url:p.url})));saveTurn('assistant',answer,pages.map(p=>({title:p.title,url:p.url})));busy=false;send.disabled=false;prompt.focus()}
  function resize(){prompt.style.height='auto';prompt.style.height=Math.min(prompt.scrollHeight,150)+'px'}
  form.addEventListener('submit',e=>{e.preventDefault();ask(prompt.value)});prompt.addEventListener('input',resize);prompt.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();form.requestSubmit()}});
  document.querySelectorAll('.suggestion').forEach(b=>b.onclick=()=>ask(b.dataset.prompt));$('#newChat').onclick=fresh;$('#teachInline').onclick=()=>modal('memoryModal');$('#memoryNav').onclick=()=>modal('memoryModal');$('#chatNav').onclick=fresh;$('#aboutButton').onclick=()=>modal('aboutModal');$('#aboutTop').onclick=()=>modal('aboutModal');$('#menuButton').onclick=()=>{ $('#sidebar').classList.add('open');$('#overlay').classList.add('show')};$('#closeSidebar').onclick=()=>{ $('#sidebar').classList.remove('open');$('#overlay').classList.remove('show')};
  function modal(id){$('#'+id).hidden=false;$('#overlay').classList.add('show');if(id==='memoryModal')renderNotes()}
  function closeModals(){$$('.modal').forEach(m=>m.hidden=true);$('#overlay').classList.remove('show')}
  function $$(s){return document.querySelectorAll(s)}
  $('#overlay').onclick=()=>{closeModals();$('#sidebar').classList.remove('open')};$$('[data-close]').forEach(b=>b.onclick=closeModals);
  $('#saveMemory').onclick=()=>{const title=$('#memoryTitleInput').value.trim()||'A note for Sprout',body=$('#memoryBody').value.trim();if(!body){$('#memoryBody').focus();return}data.notes.push({title,body,created:Date.now()});$('#memoryTitleInput').value='';$('#memoryBody').value='';persist()};
  document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();fresh()}if(e.key==='Escape')closeModals()});
  renderHistory();renderNotes();
})();
